# Generated by Django 6.1 on 2026-08-14 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adhesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre_tirage', models.PositiveIntegerField(help_text='Position dans la rotation des bénéficiaires')),
                ('actif', models.BooleanField(default=True)),
                ('date_adhesion', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhesions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ordre_tirage'],
            },
        ),
        migrations.CreateModel(
            name='Tontine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('montant_cotisation', models.DecimalField(decimal_places=2, help_text='Montant en FCFA par membre et par cycle', max_digits=12)),
                ('frequence', models.CharField(choices=[('hebdomadaire', 'Hebdomadaire'), ('mensuelle', 'Mensuelle')], default='mensuelle', max_length=20)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('fermee', 'Fermée')], default='active', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tontines_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Numéro du cycle dans la tontine (1, 2, 3...)')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé')], default='en_cours', max_length=20)),
                ('beneficiaire', models.ForeignKey(blank=True, help_text='Membre qui reçoit la cagnotte de ce cycle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycles_beneficies', to='tontines.adhesion')),
                ('tontine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='tontines.tontine')),
            ],
            options={
                'ordering': ['-numero'],
                'unique_together': {('tontine', 'numero')},
            },
        ),
        migrations.AddField(
            model_name='adhesion',
            name='tontine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhesions', to='tontines.tontine'),
        ),
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moyen_paiement', models.CharField(choices=[('orange_money', 'Orange Money'), ('moov_money', 'Moov Money'), ('airtel_money', 'Airtel Money'), ('especes', 'Espèces')], default='especes', max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('payee', 'Payée'), ('en_retard', 'En retard')], default='en_attente', max_length=20)),
                ('reference_transaction', models.CharField(blank=True, help_text='Référence de la transaction mobile money', max_length=100)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('adhesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='tontines.adhesion')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='tontines.cycle')),
            ],
            options={
                'ordering': ['-date_paiement'],
                'unique_together': {('cycle', 'adhesion')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='adhesion',
            unique_together={('tontine', 'utilisateur')},
        ),
    ]
