# Generated by Django 6.1 on 2026-08-15 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tontine',
            name='code_invitation',
            field=models.CharField(blank=True, help_text='Code à partager pour rejoindre cette tontine', max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='tontine',
            name='type_tontine',
            field=models.CharField(choices=[('individuelle', 'Individuelle (épargne personnelle)'), ('collective', "Collective (avec d'autres membres)")], default='collective', max_length=20),
        ),
        migrations.AlterField(
            model_name='cotisation',
            name='moyen_paiement',
            field=models.CharField(choices=[('orange_money', 'Orange Money'), ('moov_money', 'Moov Money'), ('airtel_money', 'Airtel Money'), ('mtn_money', 'MTN Money'), ('especes', 'Espèces')], default='especes', max_length=20),
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moyen_paiement', models.CharField(choices=[('orange_money', 'Orange Money'), ('moov_money', 'Moov Money'), ('airtel_money', 'Airtel Money'), ('mtn_money', 'MTN Money')], max_length=20)),
                ('reference_transaction', models.CharField(help_text='Référence/ID de la transaction mobile money', max_length=100)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depots_traites', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Retrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_demande', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frais', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_net', models.DecimalField(decimal_places=2, help_text="Montant réellement envoyé à l'utilisateur", max_digits=12)),
                ('moyen_paiement', models.CharField(choices=[('orange_money', 'Orange Money'), ('moov_money', 'Moov Money'), ('airtel_money', 'Airtel Money'), ('mtn_money', 'MTN Money')], max_length=20)),
                ('numero_reception', models.CharField(help_text='Numéro mobile money qui recevra les fonds', max_length=30)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé — envoyé'), ('rejete', 'Rejeté — remboursé')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retraits_traites', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retraits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
