# Generated by Django 6.1 on 2026-08-16 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontines', '0002_tontine_code_invitation_tontine_type_tontine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='tontine',
            field=models.ForeignKey(blank=True, help_text='Tontine concernée par ce dépôt', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depots', to='tontines.tontine'),
        ),
        migrations.AddField(
            model_name='retrait',
            name='tontine',
            field=models.ForeignKey(blank=True, help_text='Tontine individuelle concernée par ce retrait', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retraits', to='tontines.tontine'),
        ),
    ]
