# Generated by Django 6.1 on 2026-08-17 12:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontines', '0003_depot_tontine_retrait_tontine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adhesion',
            name='derniere_capitalisation',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Dernier point de calcul des intérêts'),
        ),
        migrations.AddField(
            model_name='adhesion',
            name='solde',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant accumulé sur cette tontine (épargne individuelle notamment)', max_digits=12),
        ),
        migrations.AddField(
            model_name='tontine',
            name='interets_actifs',
            field=models.BooleanField(default=True, help_text="Applique 5% d'intérêt tous les 30 jours (tontines individuelles uniquement)"),
        ),
        migrations.CreateModel(
            name='Interet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('solde_avant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('solde_apres', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_application', models.DateTimeField(auto_now_add=True)),
                ('adhesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interets', to='tontines.adhesion')),
            ],
            options={
                'ordering': ['-date_application'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
