# Generated by Django 6.1 on 2026-08-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='solde',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Solde disponible en FCFA', max_digits=12),
        ),
    ]
