# Generated by Django 6.1 on 2026-08-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_utilisateur_solde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(help_text='Adresse e-mail, utilisée pour la réinitialisation du mot de passe.', max_length=254, unique=True),
        ),
    ]
